export type AssetKind = 'stock' | 'etf'
export type AssetMarket = 'US' | 'BMV'
export type AssetCurrency = 'USD' | 'MXN'

export type EquityProfile = {
  symbol: string
  name: string
  kind: AssetKind
  exchange: 'NASDAQ' | 'NYSE' | 'NYSEARCA' | 'BMV'
  market?: AssetMarket
  currency?: AssetCurrency
  providerSymbols?: Partial<Record<'polygon' | 'twelvedata' | 'alphavantage' | 'stooq' | 'yahoo', string>>
  cik?: string
  sector: string
  industry: string
  index: string
  marketCap: number
  pe: number | null
  eps: number | null
  debtEquity: number | null
  pb: number | null
  roe: number | null
  dividendYield: number
  targetPrice: number | null
  analystScore: number
  socialScore: number
  beta: number
  seedPrice: number
}

export const EQUITY_CATALOG: EquityProfile[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Tecnologia',
    industry: 'Consumer electronics',
    index: 'NASDAQ 100',
    marketCap: 4500000000000,
    pe: 31.4,
    eps: 9.79,
    debtEquity: 1.45,
    pb: 47.8,
    roe: 1.47,
    dividendYield: 0.32,
    targetPrice: 318,
    analystScore: 71,
    socialScore: 63,
    beta: 1.12,
    seedPrice: 307,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Tecnologia',
    industry: 'Software infrastructure',
    index: 'NASDAQ 100',
    marketCap: 3100000000000,
    pe: 29.5,
    eps: 14.08,
    debtEquity: 0.31,
    pb: 8.6,
    roe: 0.32,
    dividendYield: 0.78,
    targetPrice: 474,
    analystScore: 84,
    socialScore: 68,
    beta: 0.91,
    seedPrice: 417,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Tecnologia',
    industry: 'Semiconductors',
    index: 'NASDAQ 100',
    marketCap: 3800000000000,
    pe: 36.8,
    eps: 4.23,
    debtEquity: 0.17,
    pb: 31.2,
    roe: 1.06,
    dividendYield: 0.03,
    targetPrice: 181,
    analystScore: 88,
    socialScore: 91,
    beta: 1.74,
    seedPrice: 156,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Consumo discrecional',
    industry: 'Auto manufacturers',
    index: 'NASDAQ 100',
    marketCap: 760000000000,
    pe: 58.7,
    eps: 3.95,
    debtEquity: 0.12,
    pb: 10.7,
    roe: 0.19,
    dividendYield: 0,
    targetPrice: 248,
    analystScore: 54,
    socialScore: 96,
    beta: 2.03,
    seedPrice: 233,
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Consumo discrecional',
    industry: 'Internet retail',
    index: 'NASDAQ 100',
    marketCap: 2200000000000,
    pe: 34.2,
    eps: 6.12,
    debtEquity: 0.51,
    pb: 8.1,
    roe: 0.26,
    dividendYield: 0,
    targetPrice: 247,
    analystScore: 82,
    socialScore: 76,
    beta: 1.2,
    seedPrice: 209,
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Comunicacion',
    industry: 'Internet content',
    index: 'NASDAQ 100',
    marketCap: 2300000000000,
    pe: 24.6,
    eps: 7.78,
    debtEquity: 0.09,
    pb: 6.4,
    roe: 0.29,
    dividendYield: 0.41,
    targetPrice: 218,
    analystScore: 80,
    socialScore: 70,
    beta: 1.04,
    seedPrice: 191,
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Comunicacion',
    industry: 'Internet content',
    index: 'NASDAQ 100',
    marketCap: 1600000000000,
    pe: 28.1,
    eps: 22.18,
    debtEquity: 0.26,
    pb: 9.2,
    roe: 0.36,
    dividendYield: 0.33,
    targetPrice: 710,
    analystScore: 78,
    socialScore: 84,
    beta: 1.18,
    seedPrice: 623,
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Tecnologia',
    industry: 'Semiconductors',
    index: 'NASDAQ 100',
    marketCap: 280000000000,
    pe: 41.9,
    eps: 4.16,
    debtEquity: 0.05,
    pb: 5.5,
    roe: 0.11,
    dividendYield: 0,
    targetPrice: 196,
    analystScore: 73,
    socialScore: 87,
    beta: 1.92,
    seedPrice: 174,
  },
  {
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Tecnologia',
    industry: 'Semiconductors',
    index: 'NASDAQ 100',
    marketCap: 1200000000000,
    pe: 32.6,
    eps: 8.13,
    debtEquity: 1.08,
    pb: 18.4,
    roe: 0.58,
    dividendYield: 0.89,
    targetPrice: 292,
    analystScore: 86,
    socialScore: 72,
    beta: 1.05,
    seedPrice: 266,
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Tecnologia',
    industry: 'Software application',
    index: 'S&P 500',
    marketCap: 270000000000,
    pe: 89.3,
    eps: 1.31,
    debtEquity: 0.06,
    pb: 25.8,
    roe: 0.18,
    dividendYield: 0,
    targetPrice: 105,
    analystScore: 57,
    socialScore: 94,
    beta: 2.04,
    seedPrice: 117,
  },
  {
    symbol: 'SOFI',
    name: 'SoFi Technologies',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Finanzas',
    industry: 'Credit services',
    index: 'Russell 2000',
    marketCap: 19000000000,
    pe: 47.1,
    eps: 0.37,
    debtEquity: 0.82,
    pb: 2.4,
    roe: 0.07,
    dividendYield: 0,
    targetPrice: 18,
    analystScore: 62,
    socialScore: 88,
    beta: 1.87,
    seedPrice: 17,
  },
  {
    symbol: 'RIVN',
    name: 'Rivian Automotive',
    kind: 'stock',
    exchange: 'NASDAQ',
    sector: 'Consumo discrecional',
    industry: 'Auto manufacturers',
    index: 'Russell 2000',
    marketCap: 16000000000,
    pe: null,
    eps: -2.6,
    debtEquity: 0.64,
    pb: 1.4,
    roe: -0.31,
    dividendYield: 0,
    targetPrice: 18,
    analystScore: 58,
    socialScore: 79,
    beta: 1.64,
    seedPrice: 15,
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase',
    kind: 'stock',
    exchange: 'NYSE',
    sector: 'Finanzas',
    industry: 'Banks diversified',
    index: 'S&P 500',
    marketCap: 820000000000,
    pe: 14.3,
    eps: 20.51,
    debtEquity: 1.2,
    pb: 2.2,
    roe: 0.16,
    dividendYield: 1.82,
    targetPrice: 315,
    analystScore: 76,
    socialScore: 48,
    beta: 1.03,
    seedPrice: 294,
  },
  {
    symbol: 'XOM',
    name: 'Exxon Mobil Corp.',
    kind: 'stock',
    exchange: 'NYSE',
    sector: 'Energia',
    industry: 'Oil and gas integrated',
    index: 'S&P 500',
    marketCap: 490000000000,
    pe: 15.2,
    eps: 7.08,
    debtEquity: 0.18,
    pb: 1.9,
    roe: 0.13,
    dividendYield: 3.55,
    targetPrice: 126,
    analystScore: 64,
    socialScore: 42,
    beta: 0.72,
    seedPrice: 108,
  },
  {
    symbol: 'KO',
    name: 'Coca-Cola Co.',
    kind: 'stock',
    exchange: 'NYSE',
    sector: 'Consumo defensivo',
    industry: 'Beverages',
    index: 'S&P 500',
    marketCap: 310000000000,
    pe: 24.4,
    eps: 2.94,
    debtEquity: 1.62,
    pb: 10.6,
    roe: 0.42,
    dividendYield: 2.69,
    targetPrice: 78,
    analystScore: 70,
    socialScore: 35,
    beta: 0.48,
    seedPrice: 72,
  },
  {
    symbol: 'AMXB',
    name: 'America Movil SAB de CV',
    kind: 'stock',
    exchange: 'BMV',
    market: 'BMV',
    currency: 'MXN',
    providerSymbols: {
      twelvedata: 'AMXB',
      alphavantage: 'AMXB.MEX',
      stooq: 'amxb.mx',
      yahoo: 'AMXB.MX',
    },
    sector: 'Comunicacion',
    industry: 'Telecom services',
    index: 'S&P/BMV IPC',
    marketCap: 930000000000,
    pe: 14.8,
    eps: 1.12,
    debtEquity: 0.93,
    pb: 2.5,
    roe: 0.16,
    dividendYield: 2.1,
    targetPrice: 18.5,
    analystScore: 68,
    socialScore: 51,
    beta: 0.82,
    seedPrice: 16.8,
  },
  {
    symbol: 'GFNORTEO',
    name: 'Grupo Financiero Banorte',
    kind: 'stock',
    exchange: 'BMV',
    market: 'BMV',
    currency: 'MXN',
    providerSymbols: {
      twelvedata: 'GFNORTEO',
      alphavantage: 'GFNORTEO.MEX',
      stooq: 'gfnorteo.mx',
      yahoo: 'GFNORTEO.MX',
    },
    sector: 'Finanzas',
    industry: 'Banks regional',
    index: 'S&P/BMV IPC',
    marketCap: 470000000000,
    pe: 10.6,
    eps: 14.2,
    debtEquity: 1.35,
    pb: 1.8,
    roe: 0.19,
    dividendYield: 5.2,
    targetPrice: 176,
    analystScore: 74,
    socialScore: 48,
    beta: 1.08,
    seedPrice: 151,
  },
  {
    symbol: 'WALMEX',
    name: 'Wal-Mart de Mexico',
    kind: 'stock',
    exchange: 'BMV',
    market: 'BMV',
    currency: 'MXN',
    providerSymbols: {
      twelvedata: 'WALMEX',
      alphavantage: 'WALMEX.MEX',
      stooq: 'walmex.mx',
      yahoo: 'WALMEX.MX',
    },
    sector: 'Consumo defensivo',
    industry: 'Discount stores',
    index: 'S&P/BMV IPC',
    marketCap: 980000000000,
    pe: 21.4,
    eps: 3.1,
    debtEquity: 0.42,
    pb: 5.7,
    roe: 0.27,
    dividendYield: 1.5,
    targetPrice: 72,
    analystScore: 72,
    socialScore: 46,
    beta: 0.62,
    seedPrice: 66,
  },
  {
    symbol: 'CEMEXCPO',
    name: 'Cemex SAB de CV',
    kind: 'stock',
    exchange: 'BMV',
    market: 'BMV',
    currency: 'MXN',
    providerSymbols: {
      twelvedata: 'CEMEXCPO',
      alphavantage: 'CEMEXCPO.MEX',
      stooq: 'cemexcpo.mx',
      yahoo: 'CEMEXCPO.MX',
    },
    sector: 'Materiales',
    industry: 'Building materials',
    index: 'S&P/BMV IPC',
    marketCap: 190000000000,
    pe: 12.9,
    eps: 1.05,
    debtEquity: 0.78,
    pb: 1.1,
    roe: 0.09,
    dividendYield: 0.8,
    targetPrice: 15.5,
    analystScore: 63,
    socialScore: 54,
    beta: 1.38,
    seedPrice: 13.6,
  },
  {
    symbol: 'FEMSAUBD',
    name: 'Fomento Economico Mexicano',
    kind: 'stock',
    exchange: 'BMV',
    market: 'BMV',
    currency: 'MXN',
    providerSymbols: {
      twelvedata: 'FEMSAUBD',
      alphavantage: 'FEMSAUBD.MEX',
      stooq: 'femsaubd.mx',
      yahoo: 'FEMSAUBD.MX',
    },
    sector: 'Consumo defensivo',
    industry: 'Beverages and retail',
    index: 'S&P/BMV IPC',
    marketCap: 710000000000,
    pe: 19.7,
    eps: 10.9,
    debtEquity: 0.67,
    pb: 2.2,
    roe: 0.12,
    dividendYield: 1.9,
    targetPrice: 238,
    analystScore: 69,
    socialScore: 47,
    beta: 0.74,
    seedPrice: 215,
  },
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF',
    kind: 'etf',
    exchange: 'NYSEARCA',
    sector: 'ETF',
    industry: 'Large blend',
    index: 'S&P 500',
    marketCap: 0,
    pe: null,
    eps: null,
    debtEquity: null,
    pb: null,
    roe: null,
    dividendYield: 1.18,
    targetPrice: null,
    analystScore: 65,
    socialScore: 59,
    beta: 1,
    seedPrice: 632,
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    kind: 'etf',
    exchange: 'NASDAQ',
    sector: 'ETF',
    industry: 'Large growth',
    index: 'NASDAQ 100',
    marketCap: 0,
    pe: null,
    eps: null,
    debtEquity: null,
    pb: null,
    roe: null,
    dividendYield: 0.55,
    targetPrice: null,
    analystScore: 69,
    socialScore: 73,
    beta: 1.08,
    seedPrice: 552,
  },
  {
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    kind: 'etf',
    exchange: 'NYSEARCA',
    sector: 'ETF',
    industry: 'Small blend',
    index: 'Russell 2000',
    marketCap: 0,
    pe: null,
    eps: null,
    debtEquity: null,
    pb: null,
    roe: null,
    dividendYield: 1.35,
    targetPrice: null,
    analystScore: 57,
    socialScore: 52,
    beta: 1.15,
    seedPrice: 214,
  },
]

export type NewsSeed = {
  title: string
  source: string
  symbol: string
  summary: string
  url: string
  category: string
}

export const FALLBACK_NEWS: NewsSeed[] = [
  {
    title: 'Tecnologia lidera el radar por fortaleza relativa en semiconductores',
    source: 'MercadoRadar Wire',
    symbol: 'NVDA',
    summary:
      'El screener marca alto volumen, momentum positivo y revisiones de analistas por encima del promedio del grupo.',
    url: 'https://www.nasdaq.com/market-activity/stocks/nvda',
    category: 'AI Mover',
  },
  {
    title: 'ETFs amplios mantienen soporte mientras el mercado espera datos macro',
    source: 'MercadoRadar Wire',
    symbol: 'SPY',
    summary:
      'La lectura de amplitud favorece vigilancia en grandes indices antes de incrementar riesgo en small caps.',
    url: 'https://www.nasdaq.com/market-activity/funds-and-etfs/spy',
    category: 'Mercados',
  },
  {
    title: 'Small caps aparecen en el panel de alto potencial por volumen relativo',
    source: 'MercadoRadar Wire',
    symbol: 'SOFI',
    summary:
      'Los filtros de precio, volumen y beta elevan la prioridad de investigacion, pero el riesgo permanece alto.',
    url: 'https://www.nasdaq.com/market-activity/stocks/sofi',
    category: 'Screener',
  },
  {
    title: 'Dividendos defensivos vuelven al centro de notificaciones',
    source: 'MercadoRadar Wire',
    symbol: 'KO',
    summary:
      'El panel de dividend yield identifica nombres defensivos para comparar contra crecimiento de tecnologia.',
    url: 'https://www.nasdaq.com/market-activity/stocks/ko',
    category: 'Dividendos',
  },
]
